name: logging-client
version: 0.0.13
description: Logging chart for fluent-bit -> Central Logging
keywords:
- fluent-bit
- eventrouter
home: https://github.com/samsung-cnct/chart-logging-client
sources:
- https://github.com/samsung-cnct/chart-logging-client
maintainers:
- name: Samsung CNCT OSS Maintainers
  email: oss-maintainer@samsung-cnct.io
icon: https://github.com/samsung-cnct/solas/docs/images/samsung-logo.svg
engine: gotpl
