name: logging-client
version: 0.0.11
description: Logging chart for fluent-bit -> Central Logging 
keywords:
- kraken
- fluent-bit
- eventrouter
home: https://github.com/samsung-cnct/chart-logging-client
sources:
- https://github.com/samsung-cnct/chart-logging-client
maintainers:
- name: Samsung CNCT
  email: samsung.cloudnative@gmail.com
icon: https://github.com/samsung-cnct/solas/docs/images/samsung-logo.svg
engine: gotpl
